spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    flyway:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ${DB_URL}
        user: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        default-schema: ${DB_SCHEMA}
        locations: classpath:db/migration