spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
   flyway:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ${FLYWAY_DB_URL}
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      default-schema: ${DB_SCHEMA}
      locations: classpath:db/migration
#    cache:
#        type: redis
#    data:
#        redis:
#            username: root
#            password: 12345
#            host: localhost
#            port: 6379
# !------> Maybe add enable this below
server:
   error:
      include-message: always
logging:
   level:
      org:
         springframework:
            jdbc:
               core:
                  JdbcTemplate:
                     DEBUG
                  StatementCreatorUtils:
                     TRACE
jwt-secret:
   ${JWT_SECRET}